[package]
name = "cheap8"
version = "0.1.0"
authors = ["Zacharie Tevaearai <zacharietevaearai@epfl.ch>"]
edition = "2018"

[workspace]
members = [
    "cheap8_sdl",
    "cheap8_core"
]

[dependencies]
cheap8_core = { path = "cheap8_core" }
